config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :microposts, only: [:create, :destroy]
  
  resources :users do
    get 'following', on: :member
    get 'followers', on: :member
  end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user

  mount_uploader :picture, PictureUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = self.email.downcase}
  before_save {self.name = self.name.capitalize}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 244}, 
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  has_many :microposts, dependent: :destroy
  scope :desc, -> {order(created_at: :desc)}

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  
  has_many :following, through: :active_relationships, source: :followed

  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'Micropost create!'
      redirect_to current_user
    else
      render 'users/show'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    redirect_to current_user
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help
    
  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find(params[:id])
    @micropost_form = current_user.microposts.build
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "#{@user.name}, welcome to the Sample App!"
      redirect_to current_user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end
319

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in'
      redirect_to root_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
require 'digest/md5'

module UserHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= link_to 'Users', users_path %>
  <%= link_to 'Profile', current_user %>
  <%= link_to 'Settings', edit_user_path(current_user) %>
  <p><%= link_to 'Log out', logout_path, method: :delete %></p>
<%else%>
  <p><%= link_to 'Log in', login_path %></p>
  <p><%= link_to 'Sign up', new_user_path %></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |message_type, message| %>
  <% message_type %> <%= message %>
<% end %>

<%= render 'layouts/header'%>

<%= yield %>

</body>
</html>

app/views/microposts/_micropost_form.html.erb
<%= form_for(@micropost_form, html: {multipart: true}) do |f| %>
  <h3><%= f.label :content %></h3>
  <p><%= f.text_area :content, placeholder: 'New micropost...' %></p>
  <p><%= f.file_field :picture %></p>
  <%= f.submit 'Add micropost'%>
<%end%>

app/views/microposts/_microposts.html.erb
<h3>All microposts:</h3>
<% @microposts.each do |micropost| %>
  <li><%= image_tag micropost.picture.url if micropost.picture? %> <%= micropost.content %>
      <%= link_to 'delete', micropost, method: :delete, data: {confirm: 'Are you sure?'} %>
  </li>
<%end%>
<%= will_paginate @microposts %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <%= pluralize(object.errors.count, "error") %>
  <% object.errors.full_messages.each do |message|%>
  <li><%= message %></li>
  <% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<%= following_user_path(@user) %>
<%= @user.following.count %>
<%= followers_user_path(@user)%>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/users/edit.html.erb
<h2>Update your profile</h2>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>  
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>  
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h2>All users</h2>
<% @users.each do |user| %>
  <li>
    <%= gravatar_for user %>
    <%= link_to user.name, user %>
    <% if logged_in? %>
      <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %>
    <% end %>
  </li>
<% end %>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2>
  <%= gravatar_for @user %>
  <%= @user.id %>.
  <%= @user.name %>
</h2>

<%= render 'microposts/micropost_form' %>
<%= render 'microposts/microposts' %>


<%= render 'shared/stats' %>